<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis maxScale="0" autoRefreshTime="0" simplifyDrawingHints="0" simplifyMaxScale="1" symbologyReferenceScale="-1" hasScaleBasedVisibilityFlag="0" simplifyLocal="1" styleCategories="AllStyleCategories" minScale="100000000" readOnly="0" simplifyAlgorithm="0" labelsEnabled="0" version="3.44.7-Solothurn" simplifyDrawingTol="1" autoRefreshMode="Disabled">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
    <Private>0</Private>
  </flags>
  <temporal durationUnit="min" endExpression="" startField="reg_datetime" durationField="fid" accumulate="0" endField="" mode="0" limitMode="0" fixedDuration="0" enabled="0" startExpression="">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <elevation respectLayerSymbol="1" zoffset="0" clamping="Terrain" customToleranceEnabled="0" binding="Centroid" type="IndividualFeatures" symbology="Line" zscale="1" showMarkerSymbolInSurfacePlots="0" extrusionEnabled="0" extrusion="0">
    <data-defined-properties>
      <Option type="Map">
        <Option value="" type="QString" name="name"/>
        <Option name="properties"/>
        <Option value="collection" type="QString" name="type"/>
      </Option>
    </data-defined-properties>
    <profileLineSymbol>
      <symbol is_animated="0" alpha="1" type="line" clip_to_extent="1" force_rhr="0" name="" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleLine" locked="0" id="{12b16c87-6147-4b80-a8a5-c4c8e1b2cb2e}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="align_dash_pattern"/>
            <Option value="square" type="QString" name="capstyle"/>
            <Option value="5;2" type="QString" name="customdash"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="customdash_map_unit_scale"/>
            <Option value="MM" type="QString" name="customdash_unit"/>
            <Option value="0" type="QString" name="dash_pattern_offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="dash_pattern_offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="dash_pattern_offset_unit"/>
            <Option value="0" type="QString" name="draw_inside_polygon"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="196,60,57,255,rgb:0.7686275,0.2352941,0.2235294,1" type="QString" name="line_color"/>
            <Option value="solid" type="QString" name="line_style"/>
            <Option value="0.6" type="QString" name="line_width"/>
            <Option value="MM" type="QString" name="line_width_unit"/>
            <Option value="0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="0" type="QString" name="ring_filter"/>
            <Option value="0" type="QString" name="trim_distance_end"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="trim_distance_end_map_unit_scale"/>
            <Option value="MM" type="QString" name="trim_distance_end_unit"/>
            <Option value="0" type="QString" name="trim_distance_start"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="trim_distance_start_map_unit_scale"/>
            <Option value="MM" type="QString" name="trim_distance_start_unit"/>
            <Option value="0" type="QString" name="tweak_dash_pattern_on_corners"/>
            <Option value="0" type="QString" name="use_custom_dash"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="width_map_unit_scale"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </profileLineSymbol>
    <profileFillSymbol>
      <symbol is_animated="0" alpha="1" type="fill" clip_to_extent="1" force_rhr="0" name="" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleFill" locked="0" id="{8b6d9310-c3f8-4847-85f4-4bd1c193b24e}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="3x:0,0,0,0,0,0" type="QString" name="border_width_map_unit_scale"/>
            <Option value="196,60,57,255,rgb:0.7686275,0.2352941,0.2235294,1" type="QString" name="color"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="140,43,41,255,rgb:0.5490196,0.1680323,0.1596704,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0.2" type="QString" name="outline_width"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="solid" type="QString" name="style"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </profileFillSymbol>
    <profileMarkerSymbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{7889b07f-85c2-4003-9584-e8ebcbd091a7}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="196,60,57,255,rgb:0.7686275,0.2352941,0.2235294,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="diamond" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="140,43,41,255,rgb:0.5490196,0.1680323,0.1596704,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0.2" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="3" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </profileMarkerSymbol>
  </elevation>
  <renderer-v2 referencescale="-1" forceraster="0" symbollevels="0" type="categorizedSymbol" enableorderby="0" attr="Category">
    <categories>
      <category value="Access Issues or Not Surveyed" render="true" uuid="{bc041f0c-22b9-4f11-92b2-cb8108feb688}" symbol="0" label="Access Issues or Not Surveyed" type="string"/>
      <category value="Dumping" render="true" uuid="{8bcf1a01-269b-4b94-8edd-aa5cfcfe6ed3}" symbol="1" label="Dumping" type="string"/>
      <category value="Encampment Trash" render="true" uuid="{cbf25780-1363-4985-999b-f5ded76248ce}" symbol="2" label="Encampment Trash" type="string"/>
      <category value="Inactive Encampment" render="true" uuid="{ea190a9c-977e-4362-80b0-bfefcb80be10}" symbol="3" label="Inactive Encampment" type="string"/>
      <category value="Litter" render="true" uuid="{a80b3137-5807-476f-8b0d-b472d8fd3ed5}" symbol="4" label="Litter" type="string"/>
      <category value="Navigation Note" render="true" uuid="{70b4e642-541c-489f-a8d3-dbc5e3c20311}" symbol="5" label="Navigation Note" type="string"/>
      <category value="Non-Removable by SDRPF" render="true" uuid="{81a94c0d-8d4f-472e-b9ed-8f3aa291d40d}" symbol="6" label="Non-Removable by SDRPF" type="string"/>
      <category value="Site No Longer Present - August 2025 to Present" render="true" uuid="{eadfa638-e3b4-46be-9e97-ba3707faa3cd}" symbol="7" label="Site No Longer Present - August 2025 to Present" type="string"/>
      <category value="Special Removal Needed" render="true" uuid="{093fe818-3eb8-47b5-a041-233fd2a2b724}" symbol="8" label="Special Removal Needed" type="string"/>
      <category value="Stormwater Debris" render="true" uuid="{a6a784bb-6aa1-4300-9682-2e546444d2f4}" symbol="9" label="Stormwater Debris" type="string"/>
      <category value="Temporary Waypoint" render="true" uuid="{e22beddd-75aa-41b6-8f70-3dd3806b28a2}" symbol="10" label="Temporary Waypoint" type="string"/>
      <category value="NULL" render="true" uuid="{3137433a-be84-49a5-9247-8cde8bbf65d9}" symbol="11" label="" type="NULL"/>
    </categories>
    <symbols>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="0" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{e167beee-9659-4b24-83ab-70c6261b797c}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAYAAAA6RwvCAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKTWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVN3WJP3Fj7f92UPVkLY8LGXbIEAIiOsCMgQWaIQkgBhhBASQMWFiApWFBURnEhVxILVCkidiOKgKLhnQYqIWotVXDjuH9yntX167+3t+9f7vOec5/zOec8PgBESJpHmomoAOVKFPDrYH49PSMTJvYACFUjgBCAQ5svCZwXFAADwA3l4fnSwP/wBr28AAgBw1S4kEsfh/4O6UCZXACCRAOAiEucLAZBSAMguVMgUAMgYALBTs2QKAJQAAGx5fEIiAKoNAOz0ST4FANipk9wXANiiHKkIAI0BAJkoRyQCQLsAYFWBUiwCwMIAoKxAIi4EwK4BgFm2MkcCgL0FAHaOWJAPQGAAgJlCLMwAIDgCAEMeE80DIEwDoDDSv+CpX3CFuEgBAMDLlc2XS9IzFLiV0Bp38vDg4iHiwmyxQmEXKRBmCeQinJebIxNI5wNMzgwAABr50cH+OD+Q5+bk4eZm52zv9MWi/mvwbyI+IfHf/ryMAgQAEE7P79pf5eXWA3DHAbB1v2upWwDaVgBo3/ldM9sJoFoK0Hr5i3k4/EAenqFQyDwdHAoLC+0lYqG9MOOLPv8z4W/gi372/EAe/tt68ABxmkCZrcCjg/1xYW52rlKO58sEQjFu9+cj/seFf/2OKdHiNLFcLBWK8ViJuFAiTcd5uVKRRCHJleIS6X8y8R+W/QmTdw0ArIZPwE62B7XLbMB+7gECiw5Y0nYAQH7zLYwaC5EAEGc0Mnn3AACTv/mPQCsBAM2XpOMAALzoGFyolBdMxggAAESggSqwQQcMwRSswA6cwR28wBcCYQZEQAwkwDwQQgbkgBwKoRiWQRlUwDrYBLWwAxqgEZrhELTBMTgN5+ASXIHrcBcGYBiewhi8hgkEQcgIE2EhOogRYo7YIs4IF5mOBCJhSDSSgKQg6YgUUSLFyHKkAqlCapFdSCPyLXIUOY1cQPqQ28ggMor8irxHMZSBslED1AJ1QLmoHxqKxqBz0XQ0D12AlqJr0Rq0Hj2AtqKn0UvodXQAfYqOY4DRMQ5mjNlhXIyHRWCJWBomxxZj5Vg1Vo81Yx1YN3YVG8CeYe8IJAKLgBPsCF6EEMJsgpCQR1hMWEOoJewjtBK6CFcJg4Qxwicik6hPtCV6EvnEeGI6sZBYRqwm7iEeIZ4lXicOE1+TSCQOyZLkTgohJZAySQtJa0jbSC2kU6Q+0hBpnEwm65Btyd7kCLKArCCXkbeQD5BPkvvJw+S3FDrFiOJMCaIkUqSUEko1ZT/lBKWfMkKZoKpRzame1AiqiDqfWkltoHZQL1OHqRM0dZolzZsWQ8ukLaPV0JppZ2n3aC/pdLoJ3YMeRZfQl9Jr6Afp5+mD9HcMDYYNg8dIYigZaxl7GacYtxkvmUymBdOXmchUMNcyG5lnmA+Yb1VYKvYqfBWRyhKVOpVWlX6V56pUVXNVP9V5qgtUq1UPq15WfaZGVbNQ46kJ1Bar1akdVbupNq7OUndSj1DPUV+jvl/9gvpjDbKGhUaghkijVGO3xhmNIRbGMmXxWELWclYD6yxrmE1iW7L57Ex2Bfsbdi97TFNDc6pmrGaRZp3mcc0BDsax4PA52ZxKziHODc57LQMtPy2x1mqtZq1+rTfaetq+2mLtcu0W7eva73VwnUCdLJ31Om0693UJuja6UbqFutt1z+o+02PreekJ9cr1Dund0Uf1bfSj9Rfq79bv0R83MDQINpAZbDE4Y/DMkGPoa5hpuNHwhOGoEctoupHEaKPRSaMnuCbuh2fjNXgXPmasbxxirDTeZdxrPGFiaTLbpMSkxeS+Kc2Ua5pmutG003TMzMgs3KzYrMnsjjnVnGueYb7ZvNv8jYWlRZzFSos2i8eW2pZ8ywWWTZb3rJhWPlZ5VvVW16xJ1lzrLOtt1ldsUBtXmwybOpvLtqitm63Edptt3xTiFI8p0in1U27aMez87ArsmuwG7Tn2YfYl9m32zx3MHBId1jt0O3xydHXMdmxwvOuk4TTDqcSpw+lXZxtnoXOd8zUXpkuQyxKXdpcXU22niqdun3rLleUa7rrStdP1o5u7m9yt2W3U3cw9xX2r+00umxvJXcM970H08PdY4nHM452nm6fC85DnL152Xlle+70eT7OcJp7WMG3I28Rb4L3Le2A6Pj1l+s7pAz7GPgKfep+Hvqa+It89viN+1n6Zfgf8nvs7+sv9j/i/4XnyFvFOBWABwQHlAb2BGoGzA2sDHwSZBKUHNQWNBbsGLww+FUIMCQ1ZH3KTb8AX8hv5YzPcZyya0RXKCJ0VWhv6MMwmTB7WEY6GzwjfEH5vpvlM6cy2CIjgR2yIuB9pGZkX+X0UKSoyqi7qUbRTdHF09yzWrORZ+2e9jvGPqYy5O9tqtnJ2Z6xqbFJsY+ybuIC4qriBeIf4RfGXEnQTJAntieTE2MQ9ieNzAudsmjOc5JpUlnRjruXcorkX5unOy553PFk1WZB8OIWYEpeyP+WDIEJQLxhP5aduTR0T8oSbhU9FvqKNolGxt7hKPJLmnVaV9jjdO31D+miGT0Z1xjMJT1IreZEZkrkj801WRNberM/ZcdktOZSclJyjUg1plrQr1zC3KLdPZisrkw3keeZtyhuTh8r35CP5c/PbFWyFTNGjtFKuUA4WTC+oK3hbGFt4uEi9SFrUM99m/ur5IwuCFny9kLBQuLCz2Lh4WfHgIr9FuxYji1MXdy4xXVK6ZHhp8NJ9y2jLspb9UOJYUlXyannc8o5Sg9KlpUMrglc0lamUycturvRauWMVYZVkVe9ql9VbVn8qF5VfrHCsqK74sEa45uJXTl/VfPV5bdra3kq3yu3rSOuk626s91m/r0q9akHV0IbwDa0b8Y3lG19tSt50oXpq9Y7NtM3KzQM1YTXtW8y2rNvyoTaj9nqdf13LVv2tq7e+2Sba1r/dd3vzDoMdFTve75TsvLUreFdrvUV99W7S7oLdjxpiG7q/5n7duEd3T8Wej3ulewf2Re/ranRvbNyvv7+yCW1SNo0eSDpw5ZuAb9qb7Zp3tXBaKg7CQeXBJ9+mfHvjUOihzsPcw83fmX+39QjrSHkr0jq/dawto22gPaG97+iMo50dXh1Hvrf/fu8x42N1xzWPV56gnSg98fnkgpPjp2Snnp1OPz3Umdx590z8mWtdUV29Z0PPnj8XdO5Mt1/3yfPe549d8Lxw9CL3Ytslt0utPa49R35w/eFIr1tv62X3y+1XPK509E3rO9Hv03/6asDVc9f41y5dn3m978bsG7duJt0cuCW69fh29u0XdwruTNxdeo94r/y+2v3qB/oP6n+0/rFlwG3g+GDAYM/DWQ/vDgmHnv6U/9OH4dJHzEfVI0YjjY+dHx8bDRq98mTOk+GnsqcTz8p+Vv9563Or59/94vtLz1j82PAL+YvPv655qfNy76uprzrHI8cfvM55PfGm/K3O233vuO+638e9H5ko/ED+UPPR+mPHp9BP9z7nfP78L/eE8/sl0p8zAABBVWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxMTEgNzkuMTU4MzI1LCAyMDE1LzA5LzEwLTAxOjEwOjIwICAgICAgICAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgICAgICAgICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iCiAgICAgICAgICAgIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiCiAgICAgICAgICAgIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIgogICAgICAgICAgICB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCk8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpDcmVhdGVEYXRlPjIwMTctMDYtMDFUMTA6NDc6NTUrMDk6MDA8L3htcDpDcmVhdGVEYXRlPgogICAgICAgICA8eG1wOk1ldGFkYXRhRGF0ZT4yMDE3LTA2LTAxVDEyOjMyOjM3KzA5OjAwPC94bXA6TWV0YWRhdGFEYXRlPgogICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAxNy0wNi0wMVQxMjozMjozNyswOTowMDwveG1wOk1vZGlmeURhdGU+CiAgICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2UvcG5nPC9kYzpmb3JtYXQ+CiAgICAgICAgIDx4bXBNTTpJbnN0YW5jZUlEPnhtcC5paWQ6OWY3NDM2MjItOWVkMC00MDJhLWFiMWQtNTNlNjdhOTMxM2UyPC94bXBNTTpJbnN0YW5jZUlEPgogICAgICAgICA8eG1wTU06RG9jdW1lbnRJRD5hZG9iZTpkb2NpZDpwaG90b3Nob3A6NWRmNDExNzgtODcwOS0xMTdhLTk2MmMtZTgyY2UyNzcwM2RmPC94bXBNTTpEb2N1bWVudElEPgogICAgICAgICA8eG1wTU06T3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6ZjQxOGZlOTktNjljZi00YTFhLTgxOWUtYWVlYjgwNzcwNWUyPC94bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ+CiAgICAgICAgIDx4bXBNTTpIaXN0b3J5PgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+Y3JlYXRlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOmY0MThmZTk5LTY5Y2YtNGExYS04MTllLWFlZWI4MDc3MDVlMjwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxNy0wNi0wMVQxMDo0Nzo1NSswOTowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5zYXZlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOjM0MDMwZTE4LWM3OTUtNDM2NC05ZGM1LTNkOTZmZTBlNjkyZDwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxNy0wNi0wMVQxMjoyOTo0MiswOTowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpjaGFuZ2VkPi88L3N0RXZ0OmNoYW5nZWQ+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5zYXZlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOmQ4NjcxOTk5LWYwMzYtNDVlNy1hODNiLTAxODhiNDU1NTM1NTwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxNy0wNi0wMVQxMjozMjozNyswOTowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpjaGFuZ2VkPi88L3N0RXZ0OmNoYW5nZWQ+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5jb252ZXJ0ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnBhcmFtZXRlcnM+ZnJvbSBhcHBsaWNhdGlvbi92bmQuYWRvYmUucGhvdG9zaG9wIHRvIGltYWdlL3BuZzwvc3RFdnQ6cGFyYW1ldGVycz4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgICAgIDxyZGY6bGkgcmRmOnBhcnNlVHlwZT0iUmVzb3VyY2UiPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6YWN0aW9uPmRlcml2ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnBhcmFtZXRlcnM+Y29udmVydGVkIGZyb20gYXBwbGljYXRpb24vdm5kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmc8L3N0RXZ0OnBhcmFtZXRlcnM+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5zYXZlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOjlmNzQzNjIyLTllZDAtNDAyYS1hYjFkLTUzZTY3YTkzMTNlMjwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxNy0wNi0wMVQxMjozMjozNyswOTowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKE1hY2ludG9zaCk8L3N0RXZ0OnNvZnR3YXJlQWdlbnQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpjaGFuZ2VkPi88L3N0RXZ0OmNoYW5nZWQ+CiAgICAgICAgICAgICAgIDwvcmRmOmxpPgogICAgICAgICAgICA8L3JkZjpTZXE+CiAgICAgICAgIDwveG1wTU06SGlzdG9yeT4KICAgICAgICAgPHhtcE1NOkRlcml2ZWRGcm9tIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgPHN0UmVmOmluc3RhbmNlSUQ+eG1wLmlpZDpkODY3MTk5OS1mMDM2LTQ1ZTctYTgzYi0wMTg4YjQ1NTUzNTU8L3N0UmVmOmluc3RhbmNlSUQ+CiAgICAgICAgICAgIDxzdFJlZjpkb2N1bWVudElEPnhtcC5kaWQ6ZjQxOGZlOTktNjljZi00YTFhLTgxOWUtYWVlYjgwNzcwNWUyPC9zdFJlZjpkb2N1bWVudElEPgogICAgICAgICAgICA8c3RSZWY6b3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6ZjQxOGZlOTktNjljZi00YTFhLTgxOWUtYWVlYjgwNzcwNWUyPC9zdFJlZjpvcmlnaW5hbERvY3VtZW50SUQ+CiAgICAgICAgIDwveG1wTU06RGVyaXZlZEZyb20+CiAgICAgICAgIDxwaG90b3Nob3A6Q29sb3JNb2RlPjM8L3Bob3Rvc2hvcDpDb2xvck1vZGU+CiAgICAgICAgIDxwaG90b3Nob3A6SUNDUHJvZmlsZT5zUkdCIElFQzYxOTY2LTIuMTwvcGhvdG9zaG9wOklDQ1Byb2ZpbGU+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjcyMDAwMC8xMDAwMDwvdGlmZjpYUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6WVJlc29sdXRpb24+NzIwMDAwLzEwMDAwPC90aWZmOllSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpSZXNvbHV0aW9uVW5pdD4yPC90aWZmOlJlc29sdXRpb25Vbml0PgogICAgICAgICA8ZXhpZjpDb2xvclNwYWNlPjE8L2V4aWY6Q29sb3JTcGFjZT4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjM0PC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjM0PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9InciPz4oU2MhAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAARYSURBVHjatJhPaBtHFMa/We0q1p9NZclgHLwluBgKxqF4QchpToEccgiFEnzyIRDoKW1CMD4kh/SUQ9NLCIZQX3tqodBLyM0EApUsjQnppYmQhLquKqmW7EorWbs7u9OLCa6j1a4k5zsJ7czbn+Z9895DhHOO4yKEwE2qqhIAl4LB4Fec80sAZEKIAACccwdAmxDy0jTNHwC8pJRyt1jvvdcvSDKZXBEE4ftwOPzR1NTUWVmWEQgE/rfGtm20223s7e21ut3uv47jrG1vb/90KiCqqsYlSfo1Eol8pihKNBgMwo9M04SmaXqn03llWdYXlNLmyCCqqn4siuJviqLMxONxghHUbDa5pml/M8aWKaV/Dg2iqmpCFMXXc3Nz52RZxjhqt9soFosVxtgFSmmjH4jgtlmSpGeKoswMgpiGBQUmFJiYhuW6TpZlKIoyI0nSM7c1gosxb0Sj0QWvdNwJ6bi7eB53F8/jTkgfeCrxeJxEo9GFZDJ5wxeIqqoCIeShoigRryMXBAHhWw8QvvUAgiB4pkhRlAgh5KGqqoInCCHkiizLUUmScNqSJAmyLEcJIVc8QSRJuplIJGR8ICUSCVmSpJueIJzzi+PekkGSZRmc84t+zBr2k+9RdRQ7fPJ7sY9H+FCROR8apt87xHF+XUeQENvfAwIBHArjmbufR3Tbtn1trvEAUK8AjRr2eMDXHtu2wTnX/Vzf561Wy1dQzXCAfypAs44685eiVqsFQshzz9SYpvm4Xq+vTE5OxryC/mVymD9vAkRApTfhC6Rerx+Ypvn4vQPo1/RSqdTr+fn5xVAo5Bn4HEwAQAXe48Hh4SHy+fzv6XT6gq+mxxi7rWmaZ36uTZhYVyJYVyK4NmF6p1LTWoyx276bXi6X2+r1em/a7fbAwMuigdDaI4TWHmFZNDxHgV6v9yaXy231e+56fS3LWi2Xy5mFhYWY2/j4yj6Dzze+ffd50HxaLpcPLMtada0tgya0VCr1XTwe/3p2dtbViZ+gBwAowN2su7u7vWaz+SSdTq+7TWgDa7llWfcbjUZF191njQImBkLouo5Go1GxLOv+UAXtuCilFmPsaqlU2vdb5E4Wr1KptM8Yu0optUYGOYJ56zjOvVKppA8LUiqVdMdx7lFK3w5d4vspk8k87Xa7L2q1muUXolarWd1u90Umk3k6Uq8Z4JeVarWqDfLLcV9Uq1XNsqyVkZvegBR1GWOXi8Vi0zDca4ZhGCgWi03G2GVKaffUQY5gyrZtX8/n861+5rVtG0fPrlNKy2ONAV7KZrNbtm2v5fN5/Xgt4Jwjn8/rtm2vZbPZrbHnEZ/m3TQMY6NQKHTe1ZNCoWMYxkYmk9kcJSYZ5m+Jk0qlUj/GYrEvAeDg4OCXdDq96n/C5GOBiACmAUQAnBEEIbi0tPQEAN/Z2fnGcRwTgAGgA6AGgH0okBCATwGcBTABICiKong0OjAAJoAegBaAPwAc+gX5bwCamT2xy31d1wAAAABJRU5ErkJggg==" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="1" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{4a6da423-ec06-4309-8d05-0f626ed8c798}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAALHRFWHRDcmVhdGlvbiBUaW1lAFR1ZSAxMCBBcHIgMjAwNyAxNToyNzoxNiAtMDUwMCO1JQMAAAAHdElNRQfXBAoTJi5YulNRAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAABGdBTUEAALGPC/xhBQAAAspJREFUeNqtVe9LU1EYfs7d3eamc+qQGYg/KBppCRGZSRGISzShMogI+tKHoPoL/BD1D/TZD33xU1CUUKiUkWE/DBVTRE3FFOfUlK3t6upu927ndLaR29p2HegLD4dz7/s+73Pe8/Ie8u2KziEYTJ+oIpfiAEzIK3DRYKBJ1OVbnxU1dJSWXLh5ELzwvu+ukMZ6u0QqB2otdU2gSlAzgDGKcCQMvWjQ9CuoOQ/fl+fnREYjoqA3gimyZkDf6Cu4PW7cab0HQkhWP9FSAhZWTWJ0s5dat2cN8+7vsJUQDE9/xFnHmT1LEiPWUssYQ994L5xOhkNlQHf3VxyzV8NqtuRArGZXPPxjAoXFQRyvjR+/vp7hzdQArp+6pEksxBUHM8IneTC6PIXWFoaFR26sdG2isZFAUryYXZ3PGrdnKd7OfUZDA4OZd4N/JABw0ZV37Whro+h5OYpqSzGMol5DMS/F/5jZWMIOlWIKEwWPLxUVBIePUAwtT2aM3SWOdkUyZDmAwZVptLczZOus5mZg3reONd9WWnxCcTiUgqG1OTgcDOXlcVaii6+CIZHFZIqTD6zOgEaVJsUndUVoN2D9TwCL217cv5UgMdhE1Dyu5HNASFFdd4JgalLF2KYLp21lmWociiGa+d3mEi62AEZj6tGjXbHwcDWtJK1twNivdUi8fP940hSPSF4wYxiFFgKXi6UQRGSKiJL+PWpV1cDghguXbeW73xLE/Jb84SDyoceH1xluq6Umtsxm+hfLTCHzizOySJyY6ES/6t8qEguK4DQXYl8WUaFIWyCifoVMXMu7zSLhJ1y3kM2fJw9Zj9YbBT4y+YMAaXFc4TFZ5ieh/PQ3ss+/JJvo0PcbrHan2V4l/t5YVNUd74uTParmyyDkQswo7Qz5f0INeKFsewjfP9hfzZJVX9X3c1COp7n456Q4pprRTg6ZIye1fwHZYJ3iSWvxpgAAAABJRU5ErkJggg==" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="10" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{485be2a9-4893-4295-b674-c8b313879775}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="174,28,214,255,hsv:0.79722222222222228,0.87058823529411766,0.83921568627450982,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="11" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{7bff76bd-6f9a-48e6-8335-111f69924a0e}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="156,124,238,255,hsv:0.71388888888888891,0.47843137254901963,0.93333333333333335,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="2" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{4ad25333-d70a-4068-a389-0e79e4e954db}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA3NpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo4ZDI3YTFmZC00ZDMyLTRiNDYtOWM1NC0yMDY3ZDg2OWJhZTIiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6NDMzNjFGNDk2MkJEMTFFNEIzQUY5QUI1NUY5ODk0OTAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6NDMzNjFGNDg2MkJEMTFFNEIzQUY5QUI1NUY5ODk0OTAiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6OGQyN2ExZmQtNGQzMi00YjQ2LTljNTQtMjA2N2Q4NjliYWUyIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjhkMjdhMWZkLTRkMzItNGI0Ni05YzU0LTIwNjdkODY5YmFlMiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PlVjc+AAAAKsSURBVHjalFRdSFRBFP7m3v27u6tEIUn4ZGSEjwuBRUr0Qz1E0EvWPiX0sCEG/RjJFlIvVr6U0L5opBuEJhVZCNWDP2VEfyqiQUIUUbi62bru3fbu3Z3O7K6w7rY/zuXjzMw555tzz5k54JwjH2iUEvYRDhIcmfrua/qqtQE5BmNsPYnTdlvJ5a1VNTBIMvyLc2J/mPY95Nz7Pz9DDrKdJFwNzhbn0SONMBrLoEUATWMYnxqtu9frriObOiI9lekr5QjQdbXF62w43gqmlWHJByzNMwT9QOXGWrSeGUL1lr0uIr2RFUwqT+nRuQ7sOXa7tbkHAT9DKACoy4AeTYLJgCxzxOIqGq9UIBwJlhJHMF+ErhPOZiJhUMksRAjTXOCvCkRC9OthIoYNjup6YV9f6Jc3byqvhK5xxDWKivImIovptBZRktSjFCGhssIh7B0FcyiywDkRxZPzxJ6Y04d4UidGHAnJChF+881/h2zgkI1kQDmTJE4QklH+WEInGRh+/JoQ9hOFCD3dvTehWAGjGTCZqAjknCAnIoOJg5kYmKTjw3SfsO/LS0gV6xgY7Byd+vIaVhuHyUqw0IUV5CSNCoOiAHf6TyIYWui42xZdKOYees66DyGo/YS9BLDYCHbAbBeEwMBQO1599IrX0iSiL6Io/P5yKOhuurAbkkWFdR1PkCl2hsnZJ3jw7OJjMmtLVMSc7ZyvMbTX1hzmw0+jfLAvyrtuzYrNr4T9Kzb9XUU2h9Rh5+jlbB+fGdu1rWoHOnvOI9UYnq/YGM28qLecPrwvXnrpQmt48/6RRmTX05VmG9ZMOLf4x4fpz2/FfCyru0jSmgmXAtQhPk2OiPlIpnKDqhdflFRhKI2MS5IsFuWZ+ksPfxdflNSBnAglzmMEHsvUv1NWR/hPgAEAnO6L9nEUPQ4AAAAASUVORK5CYII=" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="3" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{e5fa1ea4-9f8b-4b0e-b9e3-5cfcb88a669a}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA3NpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo4ZDI3YTFmZC00ZDMyLTRiNDYtOWM1NC0yMDY3ZDg2OWJhZTIiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6NDMzN0YxQkE2MkJEMTFFNEIzQUY5QUI1NUY5ODk0OTAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6NDMzN0YxQjk2MkJEMTFFNEIzQUY5QUI1NUY5ODk0OTAiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6OGQyN2ExZmQtNGQzMi00YjQ2LTljNTQtMjA2N2Q4NjliYWUyIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjhkMjdhMWZkLTRkMzItNGI0Ni05YzU0LTIwNjdkODY5YmFlMiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PqTe+4gAAAKHSURBVHjapJRLaFNBFIb/uU2axCIquLLWhUvxsWh170JBEFzpUjd1kYArUUHjTkSkgrgwCqJQQSiCiGihoIsgBUto0Var+KgtKIG0eIm35nFf439uSk1vXopDfmZyz5xvzjnzUFpr1Ddj5tzqWGsf2DO0icP9VA/1kxqjTwUtWqSVQe++upHdGWND/Ly/tw+IdQElG2p8AUqpNG2XdTiaVkDCdrJLYXBf0j/eD3RHAdclyIM2Lai7U5f0ow+9BF8g0/ybCFNIH0jiyC6oXw5gMkPHZwk8IBqBPjXAAhhJ3J+tza1rKhw1Vz2Egb5R3D4KFKuARWDFBWwHymcfJThBnx7WN/UC+Gz2kzG1ugdNokviBCMo07nEiEpMdVnANrTlUlzA8qBEB7fJ/MFOKW/HlvWMiA42IVUR4WVHtp2pe1JlaMOA6l0n83d0Auraj06+D+Wxt6VfqaHYyAfT125QLm/NsWsCfIdPS7S4UmG6O4GPwOF7NX/DFyLw1ZL5bzoBMxiehOqmyVA1KT+Aqy7JiVFJLxpbkPm32gNzySxmCxk98hpIsI4xXVOUkUUIjnCBKKN/8B7IL2e4wx/bAz1JEUO48WpUTed5RFi7GCuXqAmiiTzwbP4eR6fD7g1AnkOoiZNzkro++/wtFou8dowszsji/DpfYJIz2cCudbkjUFeKgZA99jSoZ3qcV491i8vOV6GuTWMFlmt2xRpTNkt/9PjwTRRK1/GEASvW7eEX6JJzhbCRVo9KI7BsrxUwjJffOeamTC7J/zto0xoOtvK88Cm35Pphjo/Kj+AZ/PZPQJjV8JeKXEPkFnkC5EDDbgeEvDb1amZn20pdpDaH54elmkH+p/0WYADj5Vvk123mTgAAAABJRU5ErkJggg==" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="4" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{cecaa501-1328-47e6-8f69-9096f9a0b349}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAB3RJTUUH1wQKDww5oT5AqgAAAAlwSFlzAAAewQAAHsEBw2lUUwAAAARnQU1BAACxjwv8YQUAAAMzSURBVHjarZTLbxNnFMV/4/H4lbEDDjgvSIAQlIIa2jRpm4AQrSoixFtsQEL8AaSI1wpVdFUWdF/kLlp1UakPqe2iUoF2USoQLY8GkEickIQQQuI8HGOchz2esafjSWJi7CSNlCvdxdxzz/muzne/Efqejehnz33N6EiE5YiKSh8XPzuGcOJjv15U7mPbR+8si/BfV+8gKHGsXY8HaNrTSDyRWJJAIh7jjx8vI9kc7DrSkqlveKOCX765hlVRVCS7FUVZmnB/dxuqMVmBZ2UW1+OVmRifwpr+yCd6/crPBsnDm3WNOJwFOfjgk3ZsDieeovK8fFP4dRu62h+wZWMZqpbi1+/8+NZWU9uwHadLNqac4nlnK9HwsHlggbc4r42W2YlnMzYVo731bwSHh4b3mrjwyXlkUSESDjM5HuXe1W+xoXH4eAvRyBgO96os/uz001Yk1Ffe9XbilmU8K4vpfBpEiU0QHA5RtqWQ4b4O1ldvZvfh45l+NalDUs1vxVyPetru07R9G1ZJAkHgwb//IDiL0JIpIoPdvH/wqNkXj01iEee/9JmJp8HQUD92SWB91SaShlDcWKmujnbqPzzEy9AAVlGkvLLK7A08vIucvrjEAsKJGTD4rIettW9jsYigC3R3PMK1YjWiZCcaDPBWfWOG+PDeLey+mgw37+UlVM3M8OgQgUAbY6ERUnqS1ru3Kd9Ya2JT4SB2Y73SMdDXg2rUcBRmuHNzzsTT5tfUf0Bv4D5fffkF7gIXNo/P2FXZxOXqndz883d6OttIpZIgF2d481uhzjQIIus211NRU8fowBN8a6peYWm4ZCuDL/rRIv1Ia97NwvIKq+mThWzAW1KJpmm5DFcpgpHG24FUrnDKBAxhd6GT8fAkdred5YhYJEZJmRfh+x9u6H7/b4Zvek6Tw2XDXbUCi2TJqmtxjYneqPF4cjdCtFo4e/rg6wZkx6XPf9Kv3zZ+NiWOrLrSN8mZk/tpbq6bl7+gcDqad3+q66skRKc4XRhL0ryjltOnDizItSwmfLJlH0JINfdWCyeoLC5aVPR/Ce/d2yCUlnpRhxSsuoj/8olFRZcUaUuW0v8fN+x3LcaiCRYAAAAASUVORK5CYII=" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="5" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{e1d03126-3737-45bd-a185-2a58ad04be25}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="120,203,236,255,hsv:0.54722222222222228,0.49019607843137253,0.92549019607843142,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="6" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{0de8d6aa-6dad-416a-82fd-174ceff11a73}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="216,102,126,255,hsv:0.96388888888888891,0.52941176470588236,0.84705882352941175,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="7" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{9655196b-fe81-44fa-8573-c078158f84da}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAYAAADgKtSgAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA51JREFUeNqcVctPFEkY/1V19zwdmAGEiAxGRF1A4yPxlYhZDmTNRj14wcS4CR72sBf/Fb3tntTj7h48aAwYX4mKURMVZWBQ5A0iD4cdmBf9KL/q6VWclmbdSr50V9VXv/p9z2JCCPx5OaakFhdDAKKnf0ZnJIp2zlFGW56DMftjZZZw+1UCV5JDGI9Fo9mOzpRp7/9xEaphIFJXi13tbfg9GEYz/sewTGQTfTj/4AluqSqWfr0gDE63B0niba245Am8QrK0NjhXEGrZhcvxzWiWmDf/bmLcNFHesAWHI+XY50ltKAzj0SZPFboguH83zkvMkbGkwsmvscat+MmlueCw/cxccaO99X+tQ6M8imMSk2KmcZqHFI5Y6Tmztxp6V+2Xw/E01Pr0Fx8/rEL+cY3LVQSsSkwCVyS4Rgu8FFw5Olv86S8D3hPYQBXMmXCRrTRkOITAkQ9ApTuJJKaug6nOhLlUfKRxfBoYDiJ/J26nnTAZjHkfeL9A4Jdxzyy1LDDuGSG6oPC8imgzG9g2O89hFdhnC7yG6spX8qU0mWkC/kMzYH4BYXxtGJOxzfhh3i2HPhko6p6YACLrgPM98whscyYbiKnOvlEx0ioTyoFZKE3OWuQ/MLeVVikqZQbMtAqxwhzWonhhPOPSdRH1dBr5Vd09C60u52gLMB+5oHUKYiDmyvH1ma8ClnkcaB8HP0quOkhrBYcpgRovgkBXsJhRvu9krg9UFvN40zfK/980xTr9Rhbj3AKmSze0U7S0vbB2+fscnZIiMnTkZcg1DUKCF94MI0ltV/d0YEn5rzWmpvFaUqGisyR4emkZY70v8cjzlGTYnPFUWVzADPXzLompKDBUajApKtWRpy/QRT1G27sXh1TNI9BrjLn3mOy+j6v0O0qSCocI3AnJCEng2UuYiUH0U3/fUV2FSrpMJjeviKKiuhY1EiSXRW5s1Aaw7MDryNHzlpz/iARN+8gdw/QSpevjHRa7d72FDQ4lAsReGl5PUkdSQeJ3UjUcCmLL2TM4R4e0nh509ybwmNaXZTI4XT9FMknA49Rn51StItf524JQfzzRJ7Tu1nwi+XCWXhB5YEICOsBSotkctr9JoqFuMxoJ+BqtDZL8I5PDkaz0ABHMxKKNKx2db+2nnYlVT/yNv5rYKD1Pfj8UPRfnghuc8+UwWL6B2uJOAt84Oc17IALvLCuyzCzVUvwTFrnGbPmhxmo7OWOtjsMnAQYATixfprOVfnEAAAAASUVORK5CYII=" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="8" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{8cf31959-8536-4825-977c-d0e434c0dd1b}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAYAAADgKtSgAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlhJREFUeNpi/P//PwMMfIrSdgBSCUCswEAeuADEE/iWXX0A4jDCDAcaPAFI5TNQDj4CcQHQggVgw4EGFwAF+hmoCwyZoIwCBuqDAsaPkVoGQMZ5Ghj+EeRyAQbaAH4WXDLcVRNR+P8eXmP4vnQmSaYz4ZJg1nFh+HvtBMPXtnyGP2f3Mvz/+gkszhEQycDIw0mZ4cjgz82LDCwm7hAfvH3JwO4SQJThGMHCrCDPwBFVBJG0j2Dgktdi+DaxFhhOguCgYuTih7C1LAgGFYbhjFw84CABe0tcBYx5WmSBQSEEZsMBMhuX4T2v2VXOvv8NF1D885NhCnrYKZli1fxFyoChV8CC4eypU9gNf/frP8/1d9/gAq8ZnjGUF5cQdJW2jjaDoIAAw8NPPxkefv/PICIsxPDoyVP8waKpoc7Q2duD1+BD+/cz1NTWMqxbv55h2owZDNOmTGYQFRNj8Pb1w224kb4ew8IlSxhCAgMZvn77htNwPR1dhpbmZoaZ06YxbN+5Ey5ua2XJcPjYcUT8ZdsZFGx7/AlcaHFxcoJdAc67Hz7gNFxFTY2ho72d4fqNmwzCwOCorKhgsHN0ZLh+9SqK61EMh1ng7eGBN1ju3rvLcO7iJQZsevYfPMjw5t077GH+7ft3htXAsCQF4NLDxMXCsJ4WpZYUD/t3pq695x8q8nN+oLbhctysp8Bliw4/awYXC/N/arpahospHl6H5jsYhh999X3Jux+/WSgxGBQKxkKsBqAQYUSu/UEgx96w4N2vfwGkGsrKxPhegJVxxcQD51fCxAACDABU5s23fzaB8wAAAABJRU5ErkJggg==" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="9" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="RasterMarker" locked="0" id="{c4c4abd2-63cd-4616-81c9-a8f6a663ffcf}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="1" type="QString" name="alpha"/>
            <Option value="0" type="QString" name="angle"/>
            <Option value="0" type="QString" name="fixedAspectRatio"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="base64:iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAYAAADgKtSgAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA+pJREFUeNqsVWtoXEUU/ubefd/dzWY3u3bbJFtiiDRtlUqsoamhKv7QP4UWCyr+8IeCD4pQhCIWkarFHxXrE7QqglZBpfVRFcFQa4uBotEmtjS1SbabbLOPZLO797GP+/DMNn25i9J2D9w7c86c+eacM9/MMMuy4HX1i0q56AGEAMBC0dbYoNMt9eG8MDQWi//0SvmUpsgjc9rsKGAuSE6fKpeGjcWJK20Moo98Y0vbuh7z+IKPMMZcuEqplJXvs8mZXYpVGLNgFC1rTBfI7ibgjmhw+VOSP/T4tQBzcTileyPtnXs4Fsdc1nIPE4EbIi541rYtie0gYBuuQwTRFnXb3HpBzf1WLGsqRc5aW/zBDYwJTjRBHE7PBo5J9bcTuOWxO903olnCGN8/IgdEXnM7KcJ/+YdD0lWgW+w8ZpUJi8oVdPO47diyqR9Hh19FrCOI7c8+iN6bluD5HQ/UxrntcuH6bWuW/2sBndVFzIHfensrfD4PPnjnW0gex8Uxf8Bba7c+vfliRvzb9/lzGFi/ui6HOnZw4O++PoL+9TfjxPEzDRMPBv21TJ7Z/lBNT6fySM5k/h88EPRidGwKvau6aOcdNYCeFctqgLzdvfvRWsvt6wZ7kc3kMXz0JCYnZ+vAieeRmF8K3UWMiXFDNOzH5i134uWXPqET0IID+39BJBLEm3u+qLXbtr2HlSs68cqufTRZwO/HxrGmrwfT8RT+OjkN09TzuUJqP2Ck6mr+2hvf4MihERw4uBO3D6xuWJbCgox4Yh4v7PwU7+79AQvzckPfhify/Y+G8OvwCdxPGWSyRSSmZqGoFQz9eKw2zkEviKpV8eQTr1+x8bh04626oz3c/SJdWIPNOEN6tRSfSBx/GCj9yctimIahorli0kXATyYrK8XCqWahVsva3/wGJq6YPPJCvjr3R6WkTF0vsGWZlXQ68RXHpOB1omKYFhDsajGf93pbb6Fr032NwNVUYmKvahYPkxoX4FIIPGTQS1Q1oJeIn+OiwUTRZpNMQ1dNvaqaRlVlDAITRPul1NUs2RU+RryWK5oykZqZ+lg28z9RmcdFiHPr1vbprLPtPpbMJl06jBCt30mD7fyEU9+5SFUp4Gi7NdLetZEDa3JuNJE+/SV1ZU4G8qf6WjnqTzOws/SwZgLugJZTD1u2eOag1dOxsXR6ejJNTjIFmbBgSovA9LHAQmXuXIsW7na4pG6q6YdkH6Evz5lHc3ROd/IrWrCUqC9cSRaGao8346//BVnqv5udK86LIizRQImq4RBoAl+oyycEBiSfPzabP/sZ6WcoStmCTpQTCUA3Aq6ImdN+Ni/fh38EGAA4oY4IluNBlgAAAABJRU5ErkJggg==" type="QString" name="imageFile"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="4" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </symbols>
    <source-symbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="0" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{639fd614-eb58-4dd5-b1aa-2ecbc989557f}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="190,178,151,255,rgb:0.745098,0.6980392,0.5921569,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </source-symbol>
    <rotation/>
    <sizescale/>
    <data-defined-properties>
      <Option type="Map">
        <Option value="" type="QString" name="name"/>
        <Option name="properties"/>
        <Option value="collection" type="QString" name="type"/>
      </Option>
    </data-defined-properties>
  </renderer-v2>
  <selection mode="Default">
    <selectionColor invalid="1"/>
    <selectionSymbol>
      <symbol is_animated="0" alpha="1" type="marker" clip_to_extent="1" force_rhr="0" name="" frame_rate="10">
        <data_defined_properties>
          <Option type="Map">
            <Option value="" type="QString" name="name"/>
            <Option name="properties"/>
            <Option value="collection" type="QString" name="type"/>
          </Option>
        </data_defined_properties>
        <layer class="SimpleMarker" locked="0" id="{1d6ae11d-9901-4179-b061-2c1548fbf33e}" enabled="1" pass="0">
          <Option type="Map">
            <Option value="0" type="QString" name="angle"/>
            <Option value="square" type="QString" name="cap_style"/>
            <Option value="255,0,0,255,rgb:1,0,0,1" type="QString" name="color"/>
            <Option value="1" type="QString" name="horizontal_anchor_point"/>
            <Option value="bevel" type="QString" name="joinstyle"/>
            <Option value="circle" type="QString" name="name"/>
            <Option value="0,0" type="QString" name="offset"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="offset_map_unit_scale"/>
            <Option value="MM" type="QString" name="offset_unit"/>
            <Option value="35,35,35,255,rgb:0.1372549,0.1372549,0.1372549,1" type="QString" name="outline_color"/>
            <Option value="solid" type="QString" name="outline_style"/>
            <Option value="0" type="QString" name="outline_width"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="outline_width_map_unit_scale"/>
            <Option value="MM" type="QString" name="outline_width_unit"/>
            <Option value="diameter" type="QString" name="scale_method"/>
            <Option value="2" type="QString" name="size"/>
            <Option value="3x:0,0,0,0,0,0" type="QString" name="size_map_unit_scale"/>
            <Option value="MM" type="QString" name="size_unit"/>
            <Option value="1" type="QString" name="vertical_anchor_point"/>
          </Option>
          <data_defined_properties>
            <Option type="Map">
              <Option value="" type="QString" name="name"/>
              <Option name="properties"/>
              <Option value="collection" type="QString" name="type"/>
            </Option>
          </data_defined_properties>
        </layer>
      </symbol>
    </selectionSymbol>
  </selection>
  <customproperties>
    <Option type="Map">
      <Option type="List" name="dualview/previewExpressions">
        <Option value="COALESCE( &quot;Site Name&quot;, '&lt;NULL>' )" type="QString"/>
      </Option>
      <Option value="0" type="int" name="embeddedWidgets/count"/>
      <Option type="invalid" name="variableNames"/>
      <Option type="invalid" name="variableValues"/>
    </Option>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <geometryOptions geometryPrecision="0" removeDuplicateNodes="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <legend type="default-vector" showLabelLegend="0"/>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="#" configurationFlags="NoFlag">
      <editWidget type="Range">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Latitude" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Longitude" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Site Name" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Category" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Bags of Trash" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Comments" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Image" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="uid" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="mid" configurationFlags="NoFlag">
      <editWidget type="Range">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="is_data_view_flag" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="reg_datetime" configurationFlags="NoFlag">
      <editWidget type="DateTime">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="edit_datetime" configurationFlags="NoFlag">
      <editWidget type="DateTime">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Date" configurationFlags="NoFlag">
      <editWidget type="DateTime">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="Time" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="aws_s3_images" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="login_route_type" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="data_view_count" configurationFlags="NoFlag">
      <editWidget type="Range">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="User Info" configurationFlags="NoFlag">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias index="0" name="" field="fid"/>
    <alias index="1" name="" field="#"/>
    <alias index="2" name="" field="Latitude"/>
    <alias index="3" name="" field="Longitude"/>
    <alias index="4" name="" field="Site Name"/>
    <alias index="5" name="" field="Category"/>
    <alias index="6" name="" field="Bags of Trash"/>
    <alias index="7" name="" field="Comments"/>
    <alias index="8" name="" field="Image"/>
    <alias index="9" name="" field="uid"/>
    <alias index="10" name="" field="mid"/>
    <alias index="11" name="" field="is_data_view_flag"/>
    <alias index="12" name="" field="reg_datetime"/>
    <alias index="13" name="" field="edit_datetime"/>
    <alias index="14" name="" field="Date"/>
    <alias index="15" name="" field="Time"/>
    <alias index="16" name="" field="aws_s3_images"/>
    <alias index="17" name="" field="login_route_type"/>
    <alias index="18" name="" field="data_view_count"/>
    <alias index="19" name="" field="User Info"/>
  </aliases>
  <defaults>
    <default expression="" applyOnUpdate="0" field="fid"/>
    <default expression="" applyOnUpdate="0" field="#"/>
    <default expression="" applyOnUpdate="0" field="Latitude"/>
    <default expression="" applyOnUpdate="0" field="Longitude"/>
    <default expression="" applyOnUpdate="0" field="Site Name"/>
    <default expression="" applyOnUpdate="0" field="Category"/>
    <default expression="" applyOnUpdate="0" field="Bags of Trash"/>
    <default expression="" applyOnUpdate="0" field="Comments"/>
    <default expression="" applyOnUpdate="0" field="Image"/>
    <default expression="" applyOnUpdate="0" field="uid"/>
    <default expression="" applyOnUpdate="0" field="mid"/>
    <default expression="" applyOnUpdate="0" field="is_data_view_flag"/>
    <default expression="" applyOnUpdate="0" field="reg_datetime"/>
    <default expression="" applyOnUpdate="0" field="edit_datetime"/>
    <default expression="" applyOnUpdate="0" field="Date"/>
    <default expression="" applyOnUpdate="0" field="Time"/>
    <default expression="" applyOnUpdate="0" field="aws_s3_images"/>
    <default expression="" applyOnUpdate="0" field="login_route_type"/>
    <default expression="" applyOnUpdate="0" field="data_view_count"/>
    <default expression="" applyOnUpdate="0" field="User Info"/>
  </defaults>
  <constraints>
    <constraint notnull_strength="1" exp_strength="0" unique_strength="1" constraints="3" field="fid"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="#"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Latitude"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Longitude"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Site Name"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Category"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Bags of Trash"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Comments"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Image"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="uid"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="mid"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="is_data_view_flag"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="reg_datetime"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="edit_datetime"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Date"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="Time"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="aws_s3_images"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="login_route_type"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="data_view_count"/>
    <constraint notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0" field="User Info"/>
  </constraints>
  <constraintExpressions>
    <constraint desc="" exp="" field="fid"/>
    <constraint desc="" exp="" field="#"/>
    <constraint desc="" exp="" field="Latitude"/>
    <constraint desc="" exp="" field="Longitude"/>
    <constraint desc="" exp="" field="Site Name"/>
    <constraint desc="" exp="" field="Category"/>
    <constraint desc="" exp="" field="Bags of Trash"/>
    <constraint desc="" exp="" field="Comments"/>
    <constraint desc="" exp="" field="Image"/>
    <constraint desc="" exp="" field="uid"/>
    <constraint desc="" exp="" field="mid"/>
    <constraint desc="" exp="" field="is_data_view_flag"/>
    <constraint desc="" exp="" field="reg_datetime"/>
    <constraint desc="" exp="" field="edit_datetime"/>
    <constraint desc="" exp="" field="Date"/>
    <constraint desc="" exp="" field="Time"/>
    <constraint desc="" exp="" field="aws_s3_images"/>
    <constraint desc="" exp="" field="login_route_type"/>
    <constraint desc="" exp="" field="data_view_count"/>
    <constraint desc="" exp="" field="User Info"/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction value="{00000000-0000-0000-0000-000000000000}" key="Canvas"/>
  </attributeactions>
  <attributetableconfig actionWidgetStyle="dropDown" sortOrder="0" sortExpression="&quot;fid&quot;">
    <columns>
      <column type="field" hidden="0" width="-1" name="fid"/>
      <column type="field" hidden="0" width="-1" name="#"/>
      <column type="field" hidden="0" width="-1" name="Latitude"/>
      <column type="field" hidden="0" width="-1" name="Longitude"/>
      <column type="field" hidden="0" width="-1" name="Site Name"/>
      <column type="field" hidden="0" width="-1" name="Category"/>
      <column type="field" hidden="0" width="-1" name="Bags of Trash"/>
      <column type="field" hidden="0" width="-1" name="Comments"/>
      <column type="field" hidden="0" width="-1" name="Image"/>
      <column type="field" hidden="0" width="-1" name="uid"/>
      <column type="field" hidden="0" width="-1" name="mid"/>
      <column type="field" hidden="0" width="-1" name="is_data_view_flag"/>
      <column type="field" hidden="0" width="-1" name="reg_datetime"/>
      <column type="field" hidden="0" width="-1" name="edit_datetime"/>
      <column type="field" hidden="0" width="-1" name="Date"/>
      <column type="field" hidden="0" width="-1" name="Time"/>
      <column type="field" hidden="0" width="-1" name="aws_s3_images"/>
      <column type="field" hidden="0" width="-1" name="login_route_type"/>
      <column type="field" hidden="0" width="-1" name="data_view_count"/>
      <column type="field" hidden="0" width="-1" name="User Info"/>
      <column type="actions" hidden="1" width="-1"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
    geom = feature.geometry()
    control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field editable="1" name="#"/>
    <field editable="1" name="Bags of Trash"/>
    <field editable="1" name="Category"/>
    <field editable="1" name="Comments"/>
    <field editable="1" name="Date"/>
    <field editable="1" name="Image"/>
    <field editable="1" name="Latitude"/>
    <field editable="1" name="Longitude"/>
    <field editable="1" name="Site Name"/>
    <field editable="1" name="Time"/>
    <field editable="1" name="User Info"/>
    <field editable="1" name="aws_s3_images"/>
    <field editable="1" name="data_view_count"/>
    <field editable="1" name="edit_datetime"/>
    <field editable="1" name="fid"/>
    <field editable="1" name="is_data_view_flag"/>
    <field editable="1" name="login_route_type"/>
    <field editable="1" name="mid"/>
    <field editable="1" name="reg_datetime"/>
    <field editable="1" name="uid"/>
  </editable>
  <labelOnTop>
    <field labelOnTop="0" name="#"/>
    <field labelOnTop="0" name="Bags of Trash"/>
    <field labelOnTop="0" name="Category"/>
    <field labelOnTop="0" name="Comments"/>
    <field labelOnTop="0" name="Date"/>
    <field labelOnTop="0" name="Image"/>
    <field labelOnTop="0" name="Latitude"/>
    <field labelOnTop="0" name="Longitude"/>
    <field labelOnTop="0" name="Site Name"/>
    <field labelOnTop="0" name="Time"/>
    <field labelOnTop="0" name="User Info"/>
    <field labelOnTop="0" name="aws_s3_images"/>
    <field labelOnTop="0" name="data_view_count"/>
    <field labelOnTop="0" name="edit_datetime"/>
    <field labelOnTop="0" name="fid"/>
    <field labelOnTop="0" name="is_data_view_flag"/>
    <field labelOnTop="0" name="login_route_type"/>
    <field labelOnTop="0" name="mid"/>
    <field labelOnTop="0" name="reg_datetime"/>
    <field labelOnTop="0" name="uid"/>
  </labelOnTop>
  <reuseLastValue>
    <field reuseLastValue="0" name="#"/>
    <field reuseLastValue="0" name="Bags of Trash"/>
    <field reuseLastValue="0" name="Category"/>
    <field reuseLastValue="0" name="Comments"/>
    <field reuseLastValue="0" name="Date"/>
    <field reuseLastValue="0" name="Image"/>
    <field reuseLastValue="0" name="Latitude"/>
    <field reuseLastValue="0" name="Longitude"/>
    <field reuseLastValue="0" name="Site Name"/>
    <field reuseLastValue="0" name="Time"/>
    <field reuseLastValue="0" name="User Info"/>
    <field reuseLastValue="0" name="aws_s3_images"/>
    <field reuseLastValue="0" name="data_view_count"/>
    <field reuseLastValue="0" name="edit_datetime"/>
    <field reuseLastValue="0" name="fid"/>
    <field reuseLastValue="0" name="is_data_view_flag"/>
    <field reuseLastValue="0" name="login_route_type"/>
    <field reuseLastValue="0" name="mid"/>
    <field reuseLastValue="0" name="reg_datetime"/>
    <field reuseLastValue="0" name="uid"/>
  </reuseLastValue>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>COALESCE( "Site Name", '&lt;NULL>' )</previewExpression>
  <mapTip enabled="1"></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
