# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RAFTHeatmapMkrDockWidget
                                 A QGIS plugin
 Streamlines heatmap generation for SDRPF RAFT data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alexandra Walton Weston
        email                : alexwweston@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import Qt, pyqtSignal

from ..category_enum import PinCategories

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "dockwidget.ui"))


class RaftDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()
    csvSelected = pyqtSignal(str)
    heatMapDisplaySelected = pyqtSignal()
    pinDisplaySelected = pyqtSignal()
    pinsFiltered = pyqtSignal(list)

    def __init__(self, parent=None):
        """Constructor."""
        super(RaftDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.QgsFileWidget.fileChanged.connect(self.__signal_QgsFileWidget_fileChanged)
        # PyQt5.QtWidgets.QRadioButton
        self.showHeatMap.toggled.connect(self.__showHeatmap_toggled)
        # PyQt5.QtWidgets.QGroupBox
        print(self.pinConfigBox)
        print(self.showPins)
        print(self.showHeatMap)
        # qgis._gui.QgsCheckableComboBox
        for cat in PinCategories:
            self.filterPins.addItemWithCheckState(
                cat.value, Qt.CheckState.Checked, cat.name
            )

        self.filterPins.checkedItemsChanged.connect(self.__filterPins_itemschanged)

    def reset_pin_categories(self):
        self.filterPins.selectAllOptions()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def __signal_QgsFileWidget_fileChanged(self):
        print(self.QgsFileWidget.filePath())
        self.csvSelected.emit(self.QgsFileWidget.filePath())
        self.reset_pin_categories()

    def __showHeatmap_toggled(self):
        if self.showHeatMap.isChecked():
            self.heatMapDisplaySelected.emit()
        if self.showPins.isChecked():
            self.pinDisplaySelected.emit()

    def __filterPins_itemschanged(self):
        print("items changed")
        self.pinsFiltered.emit(self.filterPins.checkedItemsData())
